services:
  web:
    build: .
    container_name: av-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=av_project.settings
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:13
    container_name: av-db
    restart: always
    environment:
      POSTGRES_DB: av_marketplace_db  # Novo banco de dados separado
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SDf872D553#41#%^@@#Dz
    volumes:
      - av_pgdata:/var/lib/postgresql/data  # Novo volume para não misturar com o antigo
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 20s

volumes:
  av_pgdata: {}  # Novo volume para o banco deste projeto

networks:
  backend: {}  # Mantendo a mesma rede
