# Generated by Django 5.1.4 on 2025-01-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_range',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Magro', 'Magro'), ('Musculoso', 'Musculoso'), ('Cheinho', 'Cheinho'), ('Plus Size', 'Plus Size')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='drinking_status',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='less_homebody',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lgbtq_status',
            field=models.CharField(blank=True, choices=[('Sim, para todos', 'Sim, para todos'), ('Apenas para amigos', 'Apenas para amigos'), ('Não estou pronto', 'Não estou pronto')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('Relacionamento sério', 'Relacionamento sério'), ('Amizade', 'Amizade'), ('Algo casual', 'Algo casual')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='more_homebody',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='nickname', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_album',
            field=models.ImageField(blank=True, null=True, upload_to='photo_albums/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_role',
            field=models.CharField(blank=True, choices=[('Dominante', 'Dominante'), ('Submisso', 'Submisso'), ('Versátil', 'Versátil')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
