"""
Django settings for av_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import ssl
import smtplib
import os

from pathlib import Path

from django.conf.global_settings import EMAIL_BACKEND

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ul02u%=kbi+@m66u%l)=v1=@stg=lnf-cp3^%5$q^(886p7zt2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'av_app',

    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # django-groups-manager
    'groups_manager',

    # django channels -redis
    'channels',

]

# django-allauth requer a identificação de qual site
SITE_ID = 1

# Redirecionamento após login
LOGIN_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'av_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'av_app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Outros context processors existentes
                'av_project.context_processors.hide_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'av_project.wsgi.application'
ASGI_APPLICATION = 'av_project.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("redis", 6379)],
        },
    },
}

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }




# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'av_marketplace_db',  # Novo banco separado
        'USER': 'postgres',
        'PASSWORD': 'SDf872D553#41#%^@@#Dz',
        'HOST': 'db',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'av_app.validators.CustomPasswordValidator',  # Nome ajustado do validador
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Diretório onde os arquivos estáticos coletados serão armazenados
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

# Diretório onde o Django buscará arquivos estáticos (mantendo como está no seu projeto)
STATICFILES_DIRS = [
    BASE_DIR / 'av_app/static',
]

# Aqui o Django irá coletar os arquivos estáticos (mantendo a pasta static e não criando staticfiles)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Adiciona o AppDirectoriesFinder, que é necessário para que o Django saiba que deve procurar arquivos no próprio Django admin
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Arquivos de mídia (imagens, arquivos enviados pelo usuário)
MEDIA_URL = '/media/'  # URL para acessar arquivos de mídia
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Diretório onde os arquivos de mídia serão armazenados

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração de e-mails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_PORT = 2525
EMAIL_HOST_USER = '535a321792feb2'
EMAIL_HOST_PASSWORD = 'dd91d588ab2762'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'noreply@seusite.com'



# Autenticação do Django Allauth - usar apenas o email como identificador
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Verificação de e-mail
ACCOUNT_USERNAME_REQUIRED = False  # Login por nome de usuário
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Autenticação por nome de usuário
ACCOUNT_EMAIL_REQUIRED = True  # E-mail obrigatório
ACCOUNT_SIGNUP_REDIRECT_URL = "/"  # Redirecionamento após cadastro
ACCOUNT_UNIQUE_EMAIL = True # Exige e-mail unico
# Número de tentativas antes do bloqueio
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/m',  # Máximo de 5 tentativas por minuto para logins falhos
}


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend padrão do Django
    'allauth.account.auth_backends.AuthenticationBackend',  # Backend do Allauth
]

