# Generated by Django 5.1.4 on 2025-02-01 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='mensagens_recebidas',
                    to=settings.AUTH_USER_MODEL
                )),
                ('remetente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='mensagens_enviadas',
                    to=settings.AUTH_USER_MODEL
                ))
            ]
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
                ('comunidade', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='posts',
                    to='groups_manager.group'
                ))
            ]
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(
                    blank=True,
                    choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado')],
                    max_length=50
                )),
                ('interests', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('looking_for', models.CharField(
                    blank=True,
                    choices=[('Relacionamento sério', 'Relacionamento sério'), ('Amizade', 'Amizade'), ('Algo casual', 'Algo casual')],
                    max_length=50
                )),
                ('age_range', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('smoking_status', models.CharField(
                    blank=True,
                    choices=[('Sim', 'Sim'), ('Não', 'Não')],
                    max_length=50
                )),
                ('drinking_status', models.CharField(
                    blank=True,
                    choices=[('Sim', 'Sim'), ('Não', 'Não')],
                    max_length=50
                )),
                ('more_homebody', models.BooleanField(default=False)),
                ('less_homebody', models.BooleanField(default=False)),
                ('body_type', models.CharField(
                    blank=True,
                    choices=[('Magro', 'Magro'), ('Musculoso', 'Musculoso'), ('Cheinho', 'Cheinho'), ('Plus Size', 'Plus Size')],
                    max_length=50
                )),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('photo_album', models.ImageField(blank=True, null=True, upload_to='photo_albums/')),
                ('lgbtq_status', models.CharField(
                    blank=True,
                    choices=[('Sim, para todos', 'Sim, para todos'), ('Apenas para amigos', 'Apenas para amigos'), ('Não estou pronto', 'Não estou pronto')],
                    max_length=50
                )),
                ('relationship_role', models.CharField(
                    blank=True,
                    choices=[('Dominante', 'Dominante'), ('Submisso', 'Submisso'), ('Versátil', 'Versátil')],
                    max_length=50
                )),
                ('role_description', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                ))
            ]
        )
    ]
