# Generated by Django 5.1.4 on 2025-02-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('av_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
