# Generated by Django 5.1.4 on 2025-02-02 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_mensagem', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_recentes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_recentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultima_mensagem'],
                'unique_together': {('usuario', 'contato')},
            },
        ),
    ]
